"""add encrypted_content_sender to messages table

Revision ID: a33b370b1c5c
Revises: 45b384865eb6
Create Date: 2025-01-22 11:46:10.002347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33b370b1c5c'
down_revision: Union[str, None] = '45b384865eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('encrypted_content_recipient', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('encrypted_content_sender', sa.String(), nullable=False))
    op.drop_column('messages', 'encrypted_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('encrypted_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'encrypted_content_sender')
    op.drop_column('messages', 'encrypted_content_recipient')
    # ### end Alembic commands ###
